name: educational_institute
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  animated_icon: ^0.0.9
  animated_notch_bottom_bar: ^1.0.1
  animations: ^2.0.11
  awesome_dialog: ^3.2.0
  countries_flag: ^1.0.0
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_otp_text_field: ^1.1.3+2
  flutter_staggered_animations: ^1.1.1
  go_router: ^14.1.4
  iconsax: ^0.0.8
  lottie: ^3.0.0
  rive: ^0.13.0
  shared_preferences: ^2.2.3
  slide_to_act: ^2.0.2
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.1.0
  url_launcher: ^6.2.6
  video_player: ^2.7.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  intl: ^0.19.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Italic.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
        - asset: assets/fonts/Ubuntu-Light.ttf
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
        - asset: assets/fonts/Ubuntu-Regular.ttf
